name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SPACES_REGION: ${{ secrets.SPACES_REGION }}
      SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run your application or deployment script
        run: |
          # Example: run tests, migrations, or deploy your app here
          # Access your secrets via environment variables, e.g.:
          echo "DB Host is: $DB_HOST"
          # python run.py  or  ./deploy.sh  as needed
